Algoritmo "Exercicio02"


Var
 lar, comp, valor_metro, area, preco : real

Inicio


 escreva("Digite a largura do terreno: ")
 leia(lar)
 escreva("Digite o comprimento do terreno: ")
 leia(comp)
 escreva("Digite o valor do metro quadrado R$ ")
 leia(valor_metro)
 
 area <- lar * comp
 preco <- area * valor_metro
 escreval()
 
 escreval("Area do terreno =", area:8:2)
 escreval("Preço do terreno = R$ ", preco:8:2)
 
 


Fimalgoritmo